# -*- coding: utf-8 -*-
"""Week 10 FinalProjectDescriptionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVY0QJL77YRaSLDlmKPMXpDiZdeubVJQ

#**Final Project - Exploring Young People Survey Data Spending Habits**
**By: Gabrielle Young**

The dataset I will be exploring looks into young people's spending habits. The dataset can be accessed [here](https://github.com/harsh543/Young-People-Survey-Dataset_Spending-Habits/blob/master/data/responses.csv).

 This dataset contains massive survey data from young people, ranging from music preferences to spending preferences. This dataset has 1011 individuals represented by each row and 151 variables.


 **Research Questions**
 1. Can we predict poor spending habits from a person's demographics? For example, if a person has more education, will they be less likely to spend more? Another example would be whether age effects spending habits. Does gender effect spending habits? To answer these questions, I would have to calcuate the proportion of spending to income.
 2. How do individuals compare to one another across similar circumstances? For example, do people with similar music preferences have similar spending habits? With this, I wanted to create a machnine learning model using many variables as inputs and most likely a combined variable averaging spending habits across individuals.

**Analysis Plan**

I want to first run some exploratory analyses:
- Distributions of the sample's demographics (gender, age, education, etc.).
- Visualize ospending habits (1 represents did not spend a lot on 5 spending very much)
- Visualize types of music in comparison to spending habits


Next, I want to create a few models to represent the data:
- logistic regression model
- random forest model
- decision tree model

This is something I have done in R, but I want to learn to do this in python.

After, I will compare the accuracy across models using their metrics and select the best model. I will then run these models on the test data and see how well they perform. I want to create a series of visualizations to illustrate performance of the models, too.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

spending= pd.read_csv('responses (2).csv')

spending.head(20)

selected_columns = spending[['Music', 'Spending on healthy eating', 'Gender', 'Age','Spending on looks', 'Spending on gadgets', 'Education', 'Entertainment spending']]
print(selected_columns)

selected_columns.head(20)

"""##**Exploratory Analysis/Visualizations**

**Descriptive Statistics - Demographics**
"""

spending[['Gender', 'Age', 'Education']].describe(include='all')
