# -*- coding: utf-8 -*-
"""Final_Project_Gabrielle_Youngipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npsYGK8HFBA0I7YlrGrjKPh3xvOJWl5p

#**Final Project - Exploring Young People Survey Data Spending Habits**
**By: Gabrielle Young**

## Dataset Description

The dataset I will be exploring looks into young people's spending habits. The dataset can be accessed [here](https://github.com/harsh543/Young-People-Survey-Dataset_Spending-Habits/blob/master/data/responses.csv).

 This dataset contains massive survey data from young people, ranging from music preferences to spending preferences. This dataset has 1011 individuals represented by each row and 151 variables. Such variables range from general demographics like age, education, or gender, to media or social preferences, like music and movie tastes or number of friends and preferences for drinking and smoking.

First, I am going to load a few packages necessary to get an initial look at the data and run some exploratory analyses.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

spending= pd.read_csv('responses (2).csv')

"""##Glimpse of the Dataset"""

spending.head(20)

"""At first glance, this is a large dataset. As much as I would love to incorporate all areas of this dataset, this would require an extensive amount of preprocessing, so we will be focusing in on a few select variables for the purposes of this project.

To frame my research questions, I have conducted a preliminary literature reivew.

## Literature Review


There is a vast amount of research that has been conducted to uncover trends between individuals and their spending habits. Overall, a few commonalities in the literature lie in educational achievement, age, gender, and even some individual preferences.

In the literature, it has been found that education has a significant impact on the types of purchases individuals make and the spending habits they develop. It has been found that individuals with lower education levels tend to have poorer spending habits. Specifically, spending habits revolve around healthy choices and discretionary spending (Lee & Capps, 2023). Specifically, it has been found that those with at most a high school level education tend to purchase food and beverages at grocery stores significantly less than others (Lee & Capps, 2023). Interestingly, households with some college education are more likely to purchase at discount stores by 0.06% and dollar stores by 1.43% (Lee & Capps, 2023). Further research also supports this trend and has found that higher education levels are correlated with more responsible spending habits (lakshmi, et al., 2017). This provides support for the idea that individuals with more education might be financially more responsible.

In addition, further research has shown that age has a significant impact on spending habits. Individuals who are older tend to have more responsible spending habits (Rambi, et al., 2001). To build on the previous research illustrating that education impacts spending habits, another source reveals that older and more educated people tend to have more planned and thought-out spending habits (Rambi, et al., 2001). Younger individuals tend to be more financially irresponsible with their spending, where they choose to spend on entertainment and luxury items, as opposed to focusing on prioritizing financial security (Alothman & Alhoshan, 2013). Overall, age has been shown to have a positive correlation with responsible spending habits, where as a person gets older, they tend to spend more responsibly (Bugheanu & Adina-Ionela, 2020).

It has also been revealed that gender differences significantly impact spending habits. Women have been found to have spending habits that differ from mens, which is unsurprising. Specifically, females tend to spend more on personal care, books, and aesthetics (Bugheanu & Adina-Ionela, 2020). Another article dives into these differences between men and women’s spending habits, and has uncovered similar trends. Women tend to spend more on items related to their looks and appearances, whereas men are more likely to spend on gadgets (Ng et al., 2020). Men and women both tend to spend a lot, but differences in the spending, according to the literature, lie within categories.

In past research, it has been revealed that household income is not a statistically significant factor in forming specific spending habits surrounding food and beverage expenses (Lee & Capps, 2023). Because of this, we will choose not to look into this factor within the study at hand.

Individual preferences for movies and types of music have been researched in the past and connected to spending habits. However, there is little backing on the majority of these studies, as they have been conducted outside of lab settings. In a few pop culture articles, it has been found that individuals with different music or movie preferences spend differently. For example, a taste for certain genres has been linked to patterns of spending, like impulse buying (Neurolaunch, 2024). Thrill seekers, or maybe individuals who enjoy thriller or horror movies, might be more likely to spend impulsively in order to gain a similar feeling of a “rush.”

Research around young adults, specifically college students, has been a focus of many studies because of their new development of individuality. Overall, college students have been found to spend more on clothes, footwear, and accessories as well as on coffee, bars, restaurants, and pubs (Bugheanu & Adina-Ionela, 2020). However, these trends need to be further studied, thus the premise of this study is to look more into young people’s spending habits.

Little empirically based research has been conducted that aims to draw a link between individual preferences and spending habits. The purpose of this study is to further investigate potential trends between music tastes and movie preferences and individual spending habits within young adults.

## Research Questions

 1. How can we predict spending habits from a person's demographics and preferences?

Hypotheses:
- If an individual has less education, then they are more likely to have poorer spending habits.
- If an indivudal is older, then  they are more likely to have better spending habits.
- Gender will have an effect on particular spending habits. If an individual identifies as a woman, then they are likely to spend more on looks. If an individual identifies as a man, then they are likely to spend more on gagets.
- If an individual likes horror movies, classical music, and is a female, maybe they will have poorer spending habits.

 2. What comparisions can we make between individual's preferences? How might these preferences be used to predict spending habits?

Hypothesis:
- If individuals share similar preferences for music, entertainment, then they are more likely to have similar spending habits.

##Analysis Plan

I want to first run some exploratory analyses and create some visualizations:
- Descriptive stats for demographics
- Distributions of the sample's demographics (gender, age, education, etc.).
- Visualize of spending habits (1 represents did not spend a lot on 5 spending very much)
- Visualize music preferences across the sample
- Visualize movie preferences across the sample

I want to create a correlation matrix across all variables previously described. I will use this to examine any potential relationships between our variables of interest.

Next, I want to create a few machine learning models to see if I can predict spending habits (an average I will calcualte across spending related variables) from a few select variables.

The models are as follows:
- linear regression model
- random forest model
- boosted tree model

After, I will compare the accuracy across models using their metrics and select the best model.

## Variables of Interest

- Education
- Gender
- Age
- Village - town
- Number of siblings
- Music: Dance, Folk, Country, Classical music, Musical, Pop, Rock, Metal or Hardrock, Punk, Hiphop/Rap, Raggae/Ska, Swing/Jazz, Rock n roll, Alternative, Latino, Techno/Trance, Opera
- Movies: Horror, Thriller, Comedy, Romantic, Sci-fi, War, Fantasy/Fairy tales, Animated, Documentary, Western, Action
- Spending habits: Entertainment spending, Spending on looks, Spending on gadgets, Spending on health

## Visualizing our Variables of Interest

First, I have chosen to select for our variables of interest and create a new dataframe.
"""

interest_variables = spending[['Music', 'Folk', 'Country', 'Classical music', 'Musical', 'Pop', 'Rock',
                               'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 'Swing, Jazz',
                               'Rock n roll', 'Alternative', 'Latino', 'Techno, Trance', 'Opera',
                               'Movies', 'Horror', 'Thriller', 'Comedy', 'Romantic', 'Sci-fi', 'War',
                               'Fantasy/Fairy tales', 'Animated', 'Documentary', 'Western', 'Action',
                               'Number of siblings', 'Dance', 'Spending on healthy eating', 'Gender',
                               'Age', 'Spending on looks', 'Spending on gadgets', 'Education',
                               'Entertainment spending', 'Village - town']]
interest_variables.head(20)

"""##**Exploratory Analysis/Visualizations**

**Descriptive Statistics - Demographics**

I have generated descriptive statstics for our demographic variables.
"""

spending[['Gender', 'Age', 'Education', 'Village - town', 'Number of siblings']].describe(include='all')

"""##Visualizations of Categorical Variables:

Now, I want to create some data visualizations to guide some of our predictions. These will also help to illustrate the contents of our dataset so we can better see where majorities and minorities may lie. In addition, we can better sift out differences between our dataset and the world, affecting the generalizability of our sample's results to the real world.

**Village-town: Place of Residence**
"""

plt.figure(figsize=(8, 5))
sns.countplot(data=spending, x='Village - town', palette="pastel")

plt.title("Distribution of Participants by Residence Type")
plt.xlabel("Residence Type (Village or City)")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""As we can see, the majority of individuals within this dataset reside in the city. This is important to consider, as it may effect our interpretations of our results. If majority of our sample resides in the city, they might have access to more stores. Will this mean that they spend more?

**Highest Level of Education Achieved**
"""

plt.figure(figsize=(8, 5))
sns.countplot(data=spending, x='Education', palette="pastel")

plt.title("Distribution of Educational Attainment Levels")
plt.xlabel("Education Level")
plt.ylabel("Frequency")

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""It appears that the majority of our sample has completed secondary school. This means our sample is fairly young, and will likely have poor generalizability because of this.

##Visualizations of Numeric Variables:

Now, I want to model a few of our numeric variables to get a sense of what our data looks like. We will start by looking at a distribution of the number of siblings across individuals.

**Number of Siblings**
"""

sns.set(style="whitegrid")

plt.figure(figsize=(8, 5))
sns.countplot(data=spending, x='Number of siblings', palette="pastel")

plt.title("Distribution of Number of Siblings Among Participants")
plt.xlabel("Number of Siblings")
plt.ylabel("Frequency")

plt.tight_layout()
plt.show()

"""The majority of our sample appears to have 1 sibling. This also may not be generalizable to other populations.

**Spending Habits**
"""

# Selecting the spending variables of interest here
spending_habits_vars = [
    'Spending on healthy eating', 'Spending on looks', 'Spending on gadgets', 'Entertainment spending'
]

spending_data = interest_variables[spending_habits_vars]

melted_spending_data = spending_data.melt(var_name='Variable', value_name='Value')

g_spending = sns.FacetGrid(melted_spending_data, col='Variable', col_wrap=5, height=3)

# Used Chat GPT to set the color scheme from like this cold to hot
# cooler tones represent less spending, warmer represent more spending
def blue_white_red(n):
    return [plt.cm.coolwarm(i/n) for i in range(n)]

g_spending.map(sns.histplot, 'Value', kde=False)

for ax in g_spending.axes.flat:
    n_bins = len(ax.patches)
    colors = blue_white_red(n_bins)

    for patch, color in zip(ax.patches, colors):
        patch.set_facecolor(color)

for ax in g_spending.axes.flat:
    ax.set_xlim([melted_spending_data['Value'].min(), melted_spending_data['Value'].max()])

g_spending.set_axis_labels('Value', 'Frequency')
g_spending.set_titles(col_template="{col_name}")

plt.tight_layout()
plt.show()

"""Half of the disributions for spending habits appear to be normally spread, centering around about a 3, or average level, of spending on looks and entertainment spreading. There is a slight right skew in the spending on helahty eating distribution, suggetsing that more individuals tend to spend more in this category. There is also a very slight left skew in spending on gadgets, suggesting that majority of individuals spend an average, or below average amount on gadgets. This is interesting and may also reflect the fact that our sample is mostly females.

**Movie Preferences**
"""

# Selecting movie variables of interest here
movies_vars = [
    'Horror', 'Thriller', 'Comedy', 'Romantic', 'Sci-fi', 'War',
    'Fantasy/Fairy tales', 'Animated', 'Documentary', 'Western', 'Action'
]

movies_data = interest_variables[movies_vars]

melted_movies_data = movies_data.melt(var_name='Variable', value_name='Value')

# Used Chat GPT to set the color scheme from like this cold to hot
# warmer tones (red/orange) represent dislike, where greens represent more of
# an interest in the movies
g_movies = sns.FacetGrid(melted_movies_data, col='Variable', col_wrap=5, height=3)

def red_white_green(n):
    return [plt.cm.RdYlGn(i/n) for i in range(n)]

g_movies.map(sns.histplot, 'Value', kde=False)

for ax in g_movies.axes.flat:
    n_bins = len(ax.patches)
    colors = red_white_green(n_bins)

    for patch, color in zip(ax.patches, colors):
        patch.set_facecolor(color)

for ax in g_movies.axes.flat:
    ax.set_xlim([melted_movies_data['Value'].min(), melted_movies_data['Value'].max()])

g_movies.set_axis_labels('Value', 'Frequency')
g_movies.set_titles(col_template="{col_name}")

plt.tight_layout()
plt.show()

"""There appears to be a large amount of variation in our movie preferences. Distributions with a skew to the left suggest that majority of our sample strongly dislikes or dislikes this genre, such as Western films. Skews to the right suggest that the sample strongly likes or likes these types of films, such as Fantasy/Fairy tales and Comedys. Distributions that appear to be more normally centered suggest that the sample does not prefer or prefer this genre, and have a neutral preference, like Sci-fi and War genres.

**Music Preferences**
"""

# Selecting music variables of interest here
music_vars = [
    'Dance', 'Music', 'Folk', 'Country', 'Classical music', 'Musical', 'Pop', 'Rock',
    'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 'Swing, Jazz',
    'Rock n roll', 'Alternative', 'Latino', 'Techno, Trance', 'Opera'
]

music_data = interest_variables[music_vars]

melted_music_data = music_data.melt(var_name='Variable', value_name='Value')

g_music = sns.FacetGrid(melted_music_data, col='Variable', col_wrap=5, height=3)

# Used Chat GPT to set the color scheme from like this cold to hot
# warmer tones (red/orange) represent dislike, where greens represent more of
# an interest in the music
def red_white_green(n):
    return [plt.cm.RdYlGn(i/n) for i in range(n)]

g_music.map(sns.histplot, 'Value', kde=False)

for ax in g_music.axes.flat:
    n_bins = len(ax.patches)
    colors = red_white_green(n_bins)

    for patch, color in zip(ax.patches, colors):
        patch.set_facecolor(color)

for ax in g_music.axes.flat:
    ax.set_xlim([melted_music_data['Value'].min(), melted_music_data['Value'].max()])

g_music.set_axis_labels('Value', 'Frequency')
g_music.set_titles(col_template="{col_name}")

plt.tight_layout()
plt.show()

"""Similarily to our movie preference distribution, there appears to be a large amount of variation in our music preferences. Distributions with a skew to the left suggest that majority of our sample strongly dislikes or dislikes this type of music, such as metal or hardrock and opera. Skews to the right suggest that the sample strongly likes or likes these types of music, such as Rock, and Pop. Distributions that appear to be more normally centered suggest that the sample does not prefer or prefer this music type, and have a neutral preference, like reggae, ska and rock n roll music types.

## Correlation Matrix

Because the majority of the variables we will be using for this data analysis are numerically coded on a scale from 1-5, I thought it would also be best to recode our categorical varaibles of interest. This preprocessing step is necessary for future analysis that will require all of our variables to be numeric.

Preprocessing steps:
- Converting our categorical variables into numeric according to this scale: 1, not strongly, to 5, very strongly
- Normalizing the variables
"""

normalized_df = interest_variables.copy()

# Normalzied number of siblings from 0-10 (min was 0, max was 10 siblings)
normalized_df['Number of siblings'] = 1 + (normalized_df['Number of siblings'] / 10 * 4)

# Assigned male as 2, and female as 4 to create more variation between the two
# genders
normalized_df['Gender'] = normalized_df['Gender'].map({'male': 2, 'female': 4})

# Assigned village as 2, and city as 4 to create more variation between the two
# areas of residence
normalized_df['Village - town'] = normalized_df['Village - town'].map({'village': 2, 'city': 4})

# Normalize age, where max age is 30 according to our descriptive statistics
normalized_df['Age'] = 1 + (normalized_df['Age'] / 30 * 4)

# Normalized education; I chose to assign graduate school levels both as 5, as
# it appears we do not have many participants within these categories
education_mapping = {
    'currently a primary school pupil': 1,
    'primary school': 2,
    'secondary school': 3,
    'college/bachelor degree': 4,
    'masters degree': 5,
    'doctorate degree': 5
}
normalized_df['Education'] = normalized_df['Education'].map(education_mapping)

normalized_df.head(20)

selected_columns = [
    'Music', 'Folk', 'Country', 'Classical music', 'Musical', 'Pop', 'Rock',
    'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 'Swing, Jazz',
    'Rock n roll', 'Alternative', 'Latino', 'Techno, Trance', 'Opera',
    'Movies', 'Horror', 'Thriller', 'Comedy', 'Romantic', 'Sci-fi', 'War',
    'Fantasy/Fairy tales', 'Animated', 'Documentary', 'Western', 'Action',
    'Number of siblings', 'Dance', 'Spending on healthy eating', 'Gender',
    'Age', 'Spending on looks', 'Spending on gadgets', 'Education',
    'Entertainment spending', 'Village - town'
]

# Created a new df only using our variables of interest from our normalized df
correlation_df = normalized_df[selected_columns]

# Used Chat GPT here, I have never created a heat map correlation matrix in
# python, but it looks awesome.
correlation_matrix = correlation_df.corr(numeric_only=True)

plt.figure(figsize=(20, 15))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlation Matrix of Selected Variables", fontsize=18)
plt.show()

"""At first glance, it appears that there are very few correlations between two individual variables. We do have a few key correlations that I would like to note:
- Age and Education
- Entertainment spending and spending on gadgets
- Gender and interest in romantic movies
- Dance and Pop music
- Opera and Classical Music
- Rock n roll and Rock music
- Thriller and Horror Movie genres

Although there are not an immense number of correlations between our variables, we cannot discount the fact that there may be potential interactions between multiple variables we are choosing to examine.

## Machine Learning Models

With this, we will move into creating a few machine learning models, that aim to predict spending habits from a vast number of variables that range from general demographics to music and movie preferences. Will knowing seemingly unrelated information make it impossible to predict individual spending habits?

For simplicity purposes, I have decided to create a single target variable for spending habits, which is the average of an individual's spending habits across all domains: healthy eating, looks, gadgets, and entertainment.

First, we will predict spending habits using a Linear Regression model.

**Linear Regression**
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error

# Set predictor columns; same variables as those of variables of interest,
# excluding our spending variables we wish to predict
predictor_columns = [
    'Music', 'Folk', 'Country', 'Classical music', 'Musical', 'Pop', 'Rock',
    'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 'Swing, Jazz',
    'Rock n roll', 'Alternative', 'Latino', 'Techno, Trance', 'Opera',
    'Movies', 'Horror', 'Thriller', 'Comedy', 'Romantic', 'Sci-fi', 'War',
    'Fantasy/Fairy tales', 'Animated', 'Documentary', 'Western', 'Action',
    'Number of siblings', 'Dance', 'Spending on healthy eating', 'Gender',
    'Age', 'Spending on looks', 'Spending on gadgets', 'Education',
    'Entertainment spending', 'Village - town'
]

#Set our target variable which we are making out of an average of all spending
# variables
spending_columns = ['Spending on healthy eating', 'Spending on looks', 'Spending on gadgets', 'Entertainment spending']
normalized_df['spending_habits'] = normalized_df[spending_columns].mean(axis=1)
target_column = 'spending_habits'

# Define the predictor variables (X) and target (Y)
X = normalized_df[predictor_columns]
y = normalized_df[target_column]

# Got this from Chat GPT using modified R code. Was not sure how to do this
# in python
preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ]), predictor_columns)
    ])

reg_model = LinearRegression()

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', reg_model)
])

# Cross-validation; set the folds as 5 which is a pretty standard value
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Extract mean RMSE (root mean squared error) - the metric we will use later to
# evaluate the model's performance
scores = cross_val_score(pipeline, X, y, cv=cv, scoring='neg_root_mean_squared_error')
print(f"Linear Regression Model RMSE: {-np.mean(scores):.4f}")

"""Now, we will repeat this process, but using a Random Forest model. The goal here is to find the best performing model for predicting our target variable: spending habits. We adjust the parameters where necessary in accordance to the demands of this model.

**Random Forest Model**
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
import numpy as np

predictor_columns = [
    'Music', 'Folk', 'Country', 'Classical music', 'Musical', 'Pop', 'Rock',
    'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 'Swing, Jazz',
    'Rock n roll', 'Alternative', 'Latino', 'Techno, Trance', 'Opera',
    'Movies', 'Horror', 'Thriller', 'Comedy', 'Romantic', 'Sci-fi', 'War',
    'Fantasy/Fairy tales', 'Animated', 'Documentary', 'Western', 'Action',
    'Number of siblings', 'Dance', 'Spending on healthy eating', 'Gender',
    'Age', 'Spending on looks', 'Spending on gadgets', 'Education',
    'Entertainment spending', 'Village - town'
]

spending_columns = ['Spending on healthy eating', 'Spending on looks', 'Spending on gadgets', 'Entertainment spending']
normalized_df['spending_habits'] = normalized_df[spending_columns].mean(axis=1)
target_column = 'spending_habits'

# Define the predictor variables (X) and target (Y)
X = normalized_df[predictor_columns]
y = normalized_df[target_column]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),  # Impute missing values with mean
            ('scaler', StandardScaler())  # Normalize numeric features
        ]), predictor_columns)
    ])

# Set the model to Random Forest here - used Chat GPT modified R code
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', rf_model)
])

cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Extract mean RMSE (root mean squared error)
scores = cross_val_score(pipeline, X, y, cv=cv, scoring='neg_root_mean_squared_error')
print(f"Random Forest Regressor RMSE: {-np.mean(scores):.4f}")

"""Lastly, we will repeat this process using a Boosted Tree model. We adjust the parameters where necessary in accordance to the demands of this model.

**Boosted Tree**
"""

from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
import numpy as np

predictor_columns = [
    'Music', 'Folk', 'Country', 'Classical music', 'Musical', 'Pop', 'Rock',
    'Metal or Hardrock', 'Punk', 'Hiphop, Rap', 'Reggae, Ska', 'Swing, Jazz',
    'Rock n roll', 'Alternative', 'Latino', 'Techno, Trance', 'Opera',
    'Movies', 'Horror', 'Thriller', 'Comedy', 'Romantic', 'Sci-fi', 'War',
    'Fantasy/Fairy tales', 'Animated', 'Documentary', 'Western', 'Action',
    'Number of siblings', 'Dance', 'Spending on healthy eating', 'Gender',
    'Age', 'Spending on looks', 'Spending on gadgets', 'Education',
    'Entertainment spending', 'Village - town'
]

spending_columns = ['Spending on healthy eating', 'Spending on looks', 'Spending on gadgets', 'Entertainment spending']
normalized_df['spending_habits'] = normalized_df[spending_columns].mean(axis=1)
target_column = 'spending_habits'

# Define the predictor variables (X) and target (Y)
X = normalized_df[predictor_columns]
y = normalized_df[target_column]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ]), predictor_columns)
    ])

# Set the model to Boosted Tree here - got from Chat GPT modified R code
boosted_tree_model = XGBRegressor(objective='reg:squarederror', n_estimators=100, random_state=42)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', boosted_tree_model)
])

cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Extract our metric mean RSME
scores = cross_val_score(pipeline, X, y, cv=cv, scoring='neg_root_mean_squared_error')
print(f"Boosted Tree (XGBoost) RMSE: {-np.mean(scores):.4f}")

"""Lastly, I want to plot our mean RMSE metrics to compare model performance. A lower mean RMSE means that the model is performing well, whereas a higher mean RMSE means the model is not performing well and has a higher average error.

**Plotting and Comparing Model Performance**
"""

# I had used this code previously in R, and had Chat GPT help me convert it in
# python to create a plot visualizing the results.

model_results = pd.DataFrame({
    'model': ['Linear Regression', 'Random Forest', 'Boosted Tree (XGBoost)'],
    'mean_rmse': [0.0147, 0.1412, 0.0887]
})

model_results_sorted = model_results.sort_values(by="mean_rmse", ascending=True)

plt.figure(figsize=(8, 5))
sns.set(style="whitegrid")

sns.pointplot(data=model_results_sorted,
              x="model",
              y="mean_rmse",
              hue="model",
              dodge=False,
              markers="o",
              linestyles="--",
              errwidth=2,
              capsize=5,
              palette="Set1")

plt.title("Best Model Performance Comparison", fontsize=16)
plt.xlabel("Model", fontsize=12)
plt.ylabel("Performance Estimate (RMSE)", fontsize=12)
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

"""## Model Interpretations

A lower RMSE value means that the models are predicting the outcome fairly well, and the models have lower average errors. With this, we can say that all of these models appear to be performing fairly well. I am honestly surprised considering that many of the variables seemed to have zero correlations with one another. This might imply that interactions are occurring between multiple variables, allowing for the models to make more accurate predictions of individual spending habits.

Overall, it appears that the linear regression model seems to have the best overall performance when utilizing mean RSME. This model has a mean RSME of 0.0147, followed by Boosted Tree with 0.0887, and then Random Forest with 0.1412.

A RSME value of 0.0147 suggests that the linear regression model is predicting spending habits within 0.0147 units of their actual values.

## Narrative

This project aims to answer two research questions: How can we predict spending habits from a person's demographics and preferences? and What comparisions can we make between individual's preferences? How might these preferences be used to predict spending habits? Based on the results of our analyses, we can conclude that we are able to make predictions on individual's spending habits from a sample of information on their personal preferences in combination with general demographic information. Although, with our analyses we are unable to make specific comparisions between individuals within the sample, but we can potentially utilize our results to draw conclusions about individuals across similar circumstances.

Based on the descriptive statistics for this dataset, we have determined that the majority of the sample is young, has completed secondary education, resides in urban areas, and is female. These demographics of this sample align with past literature looking into consumer behavior research. Specifically, females have been found to spend more particularly on looks, whereas men spend more on gadgets (Ng et al., 2020). Based on the exploratory visualizations of spending habits, we have seen that the majority of our sample tends to spend more on healthy eating as opposed to gadgets, which is in line with past research that illustrates that the majority of people tend to prioritize spending on healthy habits (Lee & Capps, 2023). This may be as a result of the dataset’s oversampling of females.

Our findings within this dataset also support the idea that those with less education tend to have poorer spending habits (lakshmi, et al., 2017). Overall, the majority of this sample has achieved an education level of secondary school. Based on this information in coordination with the distributions of spending habits across different areas, we see a trend where the majority of the sample spends an average or slightly more than average amount across all areas.

Although our correlation matrix indicates only a few strong relationships between variables, we chose to take this a step further and attempt to draw predictions and relationships between multiple variables. With this, we created three machine learning models: linear regression, random forest, and boosted tree models. In regards to the machine learning models I have created, I have found all three models appear to have fairly high performance scores. This is important to note, as we have seen few strong individual correlations between variables within the correlation matrix. This may indicate interaction effects between variables, where multiple variables combined are able to predict spending habits more accurately. The results and high performance, represented from a low mean RMSE, from these models suggest that spending behaviors are not driven by single factors, but emerge from interacting demographics and preference variables.

It is interesting to note that high performance from boosted tree and random forest models suggests that even simpler models can still have mostly accurate predictions. The variables utilized as predictors seemed uncorrelated, but when combined, accurate predictions of the combined spending habits variable were made.

All in all, both research questions and my hypotheses are supported and illustrate results that are in line with the literature.

## Limitations and Future Directions

Overall, my hypotheses have been supported by our findings in the exploratory analyses and correlation matrix. We can see that we are able to visualize spending habits across the sample that match predictions made in accordance with the literature. However, we are unable to draw specific causal conclusions, as the predictive nature of the models I have created only suggest that we are able to predict a joint measure of spending habits that is an average of the spending categories from this dataset. In addition, these analyses fail to draw direct links between singular or a few variables to this joint measure of spending habits. The correlation matrix is a visualization of relationships between one variable to another. However, I did not run analyses to directly predict this joint variable for spending habits or individual categories of spending habits from just a few predicting variables. This is because I wanted to make my models as accurate as possible, which is done so by adding as many predicting variables as possible.

Of course, I should not fail to mention the generalizability of this sample. Because this sample consists of mostly young women residing in cities, it is important to mention that the results of this study may not generalize well to to other contexts. In the future, it would be interesting to test these models on a more diverse sample that may generalize better to the real-world.

In the future, it would be interesting to expand these models to predict more targeted areas of spending, such as entertainment, looks, etc. I think it would also be important to incorporate more cross fold validations and trainings with the models to better increase their overall importance. Another future direction may be adding more predictor variables to better predict our outcome and avoid overfitting. Lots to do here, mostly involving tuning the models and attempting to get the best performance we can.

## References

Abdel, M., Saleh, H., Alothman, B., & Alhoshan, L. (2013). Impact of Gender, Age and Income on Consumers' Purchasing Responsiveness to Free-Product Samples.

Bugheanu, Alexandru-Mihai, and Adina-lonela Străchinaru. "Financial Spending Behavior Patterns Based on Education, Gender and Age" Studies in Business and Economics, vol. 15, no. 2, Lucian Blaga University of Sibiu, 2020, pp. 62-68. https://doi.org/10.2478/sbe-2020-0025

Lakshmi, V. V., Niharika, D. A., & Lahari, G. (2017). Impact of gender on consumer purchasing behaviour. IOSR Journal of Business and Management (IOSR-JBM), 19(8), 33-36. https://doi.org/10.9790/487X-1908053336

Lee K, Capps O Jr (2023) Habitual behavior of household food expenditure by store type in the United States. PLoS ONE 18(9): e0291340. https://doi.org/10.1371/journal.pone.0291340

NeuroLaunch editorial team. (2024, September 22). Spending behavior: Unraveling the psychology behind consumer choices. NeuroLaunch.com. https://neurolaunch.com/spending-behavior/

Ng, S., Bharti, M., & Faust, N. T. (2020). The Impact of Gender and Culture in Consumer Behavior. In F. M. Cheung & D. F. Halpern (Eds.), The Cambridge Handbook of the International Psychology of Women (pp. 244–257). chapter, Cambridge: Cambridge University Press.

Rumokoy, Farlane S., et al. "The Influence of Demographic Factors (Age, Gender, Education and Income) on Consumer Buying Behavior of Online Shop." Jurnal Riset Ekonomi, Manajemen, Bisnis dan Akuntansi, vol. 2, no. 1, 2014.
"""
